name: Generate

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - policy-templates/**

permissions: {}

env:
  COMPDEF: "component-definition-${{ github.run_id }}.json"
  FRAMEWORK: "SSDF"

jobs:
  generate-policy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.24'
          cache: false
          check-latest: true

      - name: Setup ORAS CLI
        uses: oras-project/setup-oras@8d34698a59f5ffe24821f0b48ab62a3de8b64b20 # v1.2.3

      - name: Setup c2pcli
        uses: jpower432/c2p-actions/actions/setup-c2pcli@0bc42f492f3a6854fe0afc99c50100db8f5e17c6 # main
        with:
          c2p-version: 'main'

      - name: Install C2P plugins
        uses: ./.github/actions/install-conforma-plugin
        with:
          version: 'conforma-update'

      - name: Create Component Definition
        run: |
          go build -C cmd/  -o ../gemara-transformer
          ./gemara-transformer component -t "GitHub Repository" -v "conforma" > "${COMPDEF}"

      - name: Add GitHub ORG to config
        env:
          ORG: ${{ github.event.repository.owner.login }}
        run: sed -i "s/{{ ORG }}/$ORG/g" configs/c2p-config.yaml

      - name: Generate policy bundle
        run: c2pcli oscal2policy -c configs/c2p-config.yaml -d "${COMPDEF}" -n "${FRAMEWORK}" -p $(go env GOPATH)/bin

      - uses: actions/upload-artifact@v4
        with:
          name: component-definition
          path: ${{ env.COMPDEF }}
          retention-days: 5

      - uses: actions/upload-artifact@v4
        with:
          name: policy
          path: policy.yaml
          retention-days: 5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push bundle
        env:
          ORG: ${{ github.event.repository.owner.login }}
        run: cd ./policies/opa/ && oras push "ghcr.io/$ORG/opa-bundle:dev" ./policy
